Repository FA24SE112-Tech-Gadgets/TechGadgetsWeb, pull requests merged in 2024-12, with the labels that each got.

#44 Migrate to prod
  .github/workflows/deploy-web.yml
  README.md
  src/components/layout/Header/index.js
Labels: update

#46 Migrate to prod
  .github/workflows/deploy-web.yml
Labels: update

#47 Migrate to prod
  src/components/layout/Header/index.js
Labels: prod migration

#48 404 page & manage keyword
  src/App.js
  src/components/layout/Header/index.js
  src/context/auth/AuthContext.js
  src/pages/404.js
  src/pages/404Seller.js
  src/pages/Admin/AdminPage.js
  src/pages/Admin/AdminSideBar.js
  src/pages/AiSearch/GadgetSearchHistory.js
  src/pages/AiSearch/NaturalLanguageSearch.js
  src/pages/Cart/cart.js
  src/pages/DetailGadget/DetailGadgetPage.js
  src/pages/Favorite/FavoritePage.js
  src/pages/Gadgets/GadgetHistory.js
  src/pages/Gadgets/GadgetHistoryDetail.js
  src/pages/Gadgets/GadgetSuggest.js
  src/pages/Home/AiFeature.js
  src/pages/Home/GadgetSuggestCurrent.js
  src/pages/Home/Products.js
  src/pages/Home/index.js
  src/pages/Manager/Gadget/ManageGadget.js
  src/pages/Manager/Gadget/ManageGadgetPage.js
  src/pages/Manager/KeyWord/CreateKeyWordGroup.js
  src/pages/Manager/KeyWord/ManagerKeyWord.js
  src/pages/Manager/Sidebar.js
  src/pages/Order/Order.js
  src/pages/Order/OrderDetail.js
  src/pages/Order/OrderTable.js
  src/pages/Profile/ProfilePage.js
  src/pages/Review/ReviewPage.js
  src/pages/Review/ReviewTable.js
  src/pages/Search/Search.js
  src/pages/Seller/Gadgets/GadgetManagement.js
  src/pages/Seller/Gadgets/GadgetManagementPage.js
  src/pages/Seller/Order/Order.js
  src/pages/Seller/Order/OrderDetailSeller.js
  src/pages/Seller/Order/OrderTable.js
  src/pages/Seller/SellerHeader.js
  src/pages/Seller/SellerProfile.js
  src/pages/SellerPage/SellerPage.js
  src/pages/SignUp/SignUpPage.js
  src/pages/SignUp/Verify.js
  src/pages/Wallet/DepositHistory.js
  src/pages/Wallet/PaymentHistory.js
  src/pages/Wallet/RefundHistory.js
  src/pages/Wallet/SellerTransfer.js
Labels: enhancement

#49 Migrate to prod
  src/App.js
  src/components/layout/Header/index.js
  src/context/auth/AuthContext.js
  src/pages/404.js
  src/pages/404Seller.js
  src/pages/Admin/AdminPage.js
  src/pages/Admin/AdminSideBar.js
  src/pages/AiSearch/GadgetSearchHistory.js
  src/pages/AiSearch/NaturalLanguageSearch.js
  src/pages/Cart/cart.js
  src/pages/DetailGadget/DetailGadgetPage.js
  src/pages/Favorite/FavoritePage.js
  src/pages/Gadgets/GadgetHistory.js
  src/pages/Gadgets/GadgetHistoryDetail.js
  src/pages/Gadgets/GadgetSuggest.js
  src/pages/Home/AiFeature.js
  src/pages/Home/GadgetSuggestCurrent.js
  src/pages/Home/Products.js
  src/pages/Home/index.js
  src/pages/Manager/Gadget/ManageGadget.js
  src/pages/Manager/Gadget/ManageGadgetPage.js
  src/pages/Manager/KeyWord/CreateKeyWordGroup.js
  src/pages/Manager/KeyWord/ManagerKeyWord.js
  src/pages/Manager/Sidebar.js
  src/pages/Order/Order.js
  src/pages/Order/OrderDetail.js
  src/pages/Order/OrderTable.js
  src/pages/Profile/ProfilePage.js
  src/pages/Review/ReviewPage.js
  src/pages/Review/ReviewTable.js
  src/pages/Search/Search.js
  src/pages/Seller/Gadgets/GadgetManagement.js
  src/pages/Seller/Gadgets/GadgetManagementPage.js
  src/pages/Seller/Order/Order.js
  src/pages/Seller/Order/OrderDetailSeller.js
  src/pages/Seller/Order/OrderTable.js
  src/pages/Seller/SellerHeader.js
  src/pages/Seller/SellerProfile.js
  src/pages/SellerPage/SellerPage.js
  src/pages/SignUp/SignUpPage.js
  src/pages/SignUp/Verify.js
  src/pages/Wallet/DepositHistory.js
  src/pages/Wallet/PaymentHistory.js
  src/pages/Wallet/RefundHistory.js
  src/pages/Wallet/SellerTransfer.js
Labels: prod migration

#50 Modify api link
  src/pages/AiSearch/NaturalLanguageSearch.js
Labels: enhancement

#51 Migrate to prod
  src/pages/AiSearch/NaturalLanguageSearch.js
Labels: prod migration

#52 Manage prompt
  src/App.js
  src/pages/Admin/AdminSideBar.js
  src/pages/AiSearch/AiSearch.css
  src/pages/AiSearch/GadgetSearchHistory.js
  src/pages/AiSearch/NaturalLanguageSearch.js
  src/pages/Manager/KeyWord/CreateKeyWordGroup.js
  src/pages/Manager/KeyWord/ManagerKeyWord.js
  src/pages/Manager/Prompts/prompts.js
  src/pages/Manager/Sidebar.js
Labels: enhancement

#53 Migrate to prod
  src/App.js
  src/pages/Admin/AdminSideBar.js
  src/pages/AiSearch/AiSearch.css
  src/pages/AiSearch/GadgetSearchHistory.js
  src/pages/AiSearch/NaturalLanguageSearch.js
  src/pages/Manager/KeyWord/CreateKeyWordGroup.js
  src/pages/Manager/KeyWord/ManagerKeyWord.js
  src/pages/Manager/Prompts/prompts.js
  src/pages/Manager/Sidebar.js
Labels: prod migration

#55 Migrate to prod
  src/pages/AiSearch/NaturalLanguageSearch.js
Labels: prod migration

#56 Fix manage keyword search
  src/pages/AiSearch/NaturalLanguageSearch.js
  src/pages/Manager/KeyWord/ManagerKeyWord.js
  src/pages/Manager/Prompts/prompts.js
Labels: enhancement

#57 Migrate to prod
  src/pages/AiSearch/NaturalLanguageSearch.js
  src/pages/Manager/KeyWord/ManagerKeyWord.js
  src/pages/Manager/Prompts/prompts.js
Labels: prod migration

#58 Fix
  src/pages/Manager/Prompts/prompts.js
Labels: enhancement

#59 Migrate to prod
  src/pages/Manager/Prompts/prompts.js
Labels: prod migration

#60 Fix UI
  src/pages/Home/AiFeature.js
Labels: enhancement

#61 Migrate to prod
  src/pages/Home/AiFeature.js
Labels: prod migration
